		<!-- swimbi code start -->
		<link rel="stylesheet" type="text/css" href="menu_files/swimbi.css"/>
		<img id="logo" src="./imagenes/logo1.png">
		<div id="swimbi" style="display:inline-block;">
		    <ul>
		        <li><a href="index.php" title="Inicio">Inicio</a></li>
		        <li><a href="javascript:void(0);">Consultorio</a>
		            <ul>
		                <li><a href="javascript:void(0);" onclick="go(6);">Turnos</a></li>
		                <li><a href="javascript:void(0);" onclick="go(5);">Definición de agendas</a></li>
		            </ul>
		        </li>
		        <li><a href="javascript:void(0);">Reportes</a>
		            <ul>
		                <li><a href="javascript:void(0);" onclick="go(8);">Reportes de agendas</a></li>
		                <li><a href="#">Reportes de productividad</a></li>
		            </ul>
		        </li>
		        <li><a href="javascript:void(0);">Administración</a>
		            <ul>
		                <li><a href="javascript:void(0);">Maestros</a>
		                    <ul>
		                        <li><a href="javascript:void(0);" onclick="go(4);">Consultorios</a></li>
		                        <li><a href="javascript:void(0);" onclick="go(2);">Profesionales</a></li>
		                        <li><a href="javascript:void(0);" onclick="go(3);">Especialidades</a></li>
		                        <li><a href="javascript:void(0);" onclick="go(1);">Pacientes</a></li>
		                        <li><a href="javascript:void(0);" onclick="go(9);">Prepagas</a></li>
		                        <li><a href="javascript:void(0);" onclick="go(10);">Usuarios</a></li>
 
		                    </ul>
		                </li>
		                <li><a href="javascript:logoff();">Cerrar sesión</a></li>
		            </ul>
		        </li>
		    </ul>
		<canvas><noscript>Free swimbi menu builder in to generated by swimbi.com. All Rights Reserved</noscript></canvas>
		<div id="ie_message"><noscript>Local test in IE is better if you "<a href="http://f-source.com/swimbi/ie-allow-blocked-content/" target="_blank">Allow blocked content</a>" - click the button below.</noscript></div>
		</div>
		<script src="menu_files/swimbi.js"></script>
		<!-- swimbi code end -->